### ISSUE TITLE
Kea HTTP ctrl-agent support

### ISSUE THREAD

**Issue by Qwiko** [mweinelt/kea-exporter#33]
I think it would be a good idea to continue developing this repository.
I would like to help rebuilding to support both sockets and http "backends".
I see someone have already implemented a http-version but it is rather outdated.
https://github.com/ddericco/kea_exporter/tree/master

I can also see that a docker container with http metric support would be very useful for kubernetes deployments with automatic prometheus discovery. Configurable either with environment-variables or a configmap/configfile.

**Comment by Qwiko** [comment]
I am testing towards kea version 2.4

**Comment by mweinelt** [comment]
On a conference, will hopefully have a chance to take a look next week.

**Comment by Qwiko** [comment]
Pull request: #40 adds docker support.
I think it should be added to version 0.6.0.

**Comment by mweinelt** [comment]
I will tag another release once the currently active PRs are in. That should only take a few days. Sorry for not making a release with HTTP support earlier.

**Comment by mweinelt** [comment]
Has been released in 0.6.0

**Comment by M0NsTeRRR** [comment]
> I think it would be a good idea to continue developing this repository. I would like to help rebuilding to support both sockets and http "backends". I see someone have already implemented a http-version but it is rather outdated. https://github.com/ddericco/kea_exporter/tree/master
> 
> I can also see that a docker container with http metric support would be very useful for kubernetes deployments with automatic prometheus discovery. Configurable either with environment-variables or a configmap/configfile.

I've just deployed the exporter on a kubernetes environment with helm and it works like a charm :)
I will update this weekend the kea-exporter dashboard :)

**Comment by M0NsTeRRR** [comment]
Here is my basic helm chart for my homelab, I post it here as reference if someone wants an example in the future :)
https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/kea-exporter

i've integrated the serviceMonitor & prometheus rule to notify if the exporter is down or if a dhcp pool is over 90% :)

**Comment by M0NsTeRRR** [comment]
Dashboard updated. I've also updated the screenshots, although they are not currently displayed due to Grafana caching.

**Comment by Qwiko** [comment]
@M0NsTeRRR I am using your helm-chart now in my environment with argocd and it works very well!
I have 2 dhcp servers with HA and using multiple targets in one pod overwrites metrics from each other.
I am instead using a parent chart with your chart as a dependency with different aliases so I get individual statistics from each server.

Chart.yaml
```yaml
apiVersion: v2
name: kea-exporter
version: 0.0.1
dependencies:
  - name: kea-exporter
    alias: keadhcp-01
    version: 0.1.2
    repository: https://helm-charts.adminafk.fr
  - name: kea-exporter
    alias: keadhcp-02
    version: 0.1.2
    repository: https://helm-charts.adminafk.fr
```

values.yaml
```yaml
keadhcp-01:
  extraEnv: 
    - name: TARGETS
      value: "http://keadhcp-01:8000"

keadhcp-02:
  extraEnv: 
    - name: TARGETS
      value: "http://keadhcp-02:8000"
```
