### ISSUE TITLE
Support multiple targets with one exporter

### ISSUE THREAD

**Issue by M0NsTeRRR** [mweinelt/kea-exporter#60]
If we introduce a breaking change in #55, it would be nice to support multiple instances with a single exporter, similar to how the Blackbox Exporter works, by using a parameter to reference the target defined in a configuration file.

For example:

`config.yaml`  
```yaml
targets:
  kea1:
    url: https://kea1.example.com
    [...]
  kea2:
    url: https://kea2.example.com
    [...]
```

Access the exporter using URLs like:  
- `https://kea-exporter.example.com?target=kea1`  
- `https://kea-exporter.example.com?target=kea2`
